// Copyright (c) 2026 Paulo Vidal (https://x.com/inevitable360, https://github.com/qlpqlp)
// Copyright (c) 2026 Dogecoin Foundation
//
// SPDX-License-Identifier: MIT
// See LICENSE for copyright attribution to upstream Bitcoin/Dogecoin Core.

package rpc

// CookbookExampleParams returns copy-paste example JSON-RPC params for integrators.
// Placeholders: WALLET (P2PKH address), BLOCKHASH, TXID, HEX, ADDRESS, HOST:44556 (testnet P2P).
func CookbookExampleParams(method string) []any {
	if p, ok := cookbookExampleParams[method]; ok {
		out := make([]any, len(p))
		copy(out, p)
		return out
	}
	return []any{}
}

// cookbookExampleParams maps RPC method names to example positional params.
// Methods omitted here use an empty params array (no arguments).
var cookbookExampleParams = map[string][]any{
	"addmultisigaddress":     {2, []any{"ADDRESS1", "ADDRESS2"}, "multisig"},
	"addnode":                {"HOST:44556", "add"},
	"addwitnessaddress":      {"ADDRESS"},
	"abandontransaction":     {"TXID"},
	"bumpfee":                  {"TXID"},
	"psbtbumpfee":              {"TXID", map[string]any{}},
	"combinerawtransaction":  {[]any{"HEX1", "HEX2"}},
	"createauxblock":         {"WALLET"},
	"createmultisig":         {2, []any{"ADDRESS1", "ADDRESS2"}},
	"createpsbt": {
		[]any{map[string]any{"txid": "TXID", "vout": 0}},
		[]any{map[string]any{"WALLET": map[string]any{"": 10.0}, "subtractFeeFromOutputs": []any{0}}},
		0,
		true,
		map[string]any{"replaceable": true},
	},
	"createrawtransaction": {
		[]any{map[string]any{"txid": "TXID", "vout": 0}},
		map[string]any{"WALLET": 10.0},
	},
	"converttopsbt":          {"HEX", true},
	"decoderawtransaction":   {"HEX"},
	"decodepsbt":             {"PSBT_HEX"},
	"analyzepsbt":            {"PSBT_HEX"},
	"combinepsbt":            {[]any{"PSBT1", "PSBT2"}},
	"joinpsbts":              {[]any{"PSBT1", "PSBT2"}},
	"finalizepsbt":           {"PSBT_HEX", true},
	"utxoupdatepsbt":         {"PSBT_HEX", []any{}},
	"decodescript":           {"SCRIPT_HEX"},
	"disconnectnode":         {"HOST:44556"},
	"dogego_importmnemonic":  {"word1 word2 word3 ...", "", false},
	"dogego_importbip38":     {"6P...", "passphrase"},
	"dogego_importwalletdat": {"/path/to/wallet.dat"},
	"dogego_createpqcarrier": {map[string]any{"label": "demo"}},
	"dogego_sendpqcarrier":   {"carrier_id", "recipient"},
	"dogego_verifypqcarrier": {"carrier_id"},
	"dumpprivkey":            {"WALLET"},
	"dumpwallet":             {"/path/to/backup.txt"},
	"echo":                   {"hello"},
	"echojson":               {"hello", 42},
	"encryptwallet":          {"passphrase"},
	"estimatefee":            {6},
	"estimatepriority":       {6},
	"estimaterawfee":         {6, 2.0},
	"estimatesmartfee":       {6, "CONSERVATIVE"},
	"estimatesmartpriority":  {6},
	"getdescriptorinfo":      {"addr(WALLET)"},
	"deriveaddresses":        {"addr(WALLET)", []any{}},
	"extractdescriptor":      {"WALLET"},
	"fundrawtransaction":     {"HEX", map[string]any{"changeAddress": "WALLET"}},
	"generate":               {1},
	"generatetoaddress":      {1, "WALLET"},
	"getaccount":             {"WALLET"},
	"getaccountaddress":      {"default"},
	"getaddressinfo":         {"WALLET"},
	"getaddednodeinfo":       {true},
	"getaddressesbyaccount":  {"default"},
	"getaddressesbylabel":    {"receive"},
	"getblock":               {"BLOCKHASH", 1},
	"getblockfilter":         {"BLOCKHASH", "basic"},
	"getblockfilterheader":   {"BLOCKHASH", "basic"},
	"getblockhash":           {0},
	"getblockheader":         {"BLOCKHASH"},
	"getblockstats":          {"BLOCKHASH"},
	"getblocktemplate":       {map[string]any{"rules": []any{"segwit"}}},
	"getchaintxstats":        {2016, "BLOCKHASH"},
	"getdeploymentinfo":      {"BLOCKHASH"},
	"getindexinfo":           {"txindex"},
	"getmempoolancestors":    {"TXID"},
	"getmempooldescendants":  {"TXID"},
	"getmempoolentry":        {"TXID"},
	"mempoolexists":          {"TXID"},
	"getnewaddress":          {"receive", "legacy"},
	"getrawchangeaddress":    {"legacy"},
	"getrawtransaction":      {"TXID", true},
	"getreceivedbyaccount":   {"default", 0},
	"getreceivedbyaddress":   {"WALLET", 0},
	"getreceivedbylabel":     {"receive", 0},
	"gettransaction":         {"TXID", true},
	"gettxout":               {"TXID", 0, true},
	"gettxoutproof":          {[]any{"TXID"}, "BLOCKHASH"},
	"gettxspendingprevout":   {[]any{map[string]any{"txid": "TXID", "vout": 0}}},
	"scanblocks":             {"basic", []any{"BLOCKHASH"}, []any{}, map[string]any{}},
	"scantxoutset":           {"start", []any{"addr(WALLET)"}},
	"help":                   {"getpeerinfo"},
	"importaddress":          {"WALLET", "imported", false, true},
	"importdescriptors":      {[]any{map[string]any{"desc": "addr(WALLET)", "timestamp": 0}}},
	"importmulti":            {[]any{map[string]any{"scriptPubKey": map[string]any{"address": "WALLET"}, "timestamp": 0}}},
	"importprivkey":          {"WHEX", "label", false},
	"importprunedfunds":      {"HEX", map[string]any{"txid": "TXID", "vout": 0, "amount": 1.0, "height": 1}},
	"importpubkey":           {"HEX", "label", false},
	"importwallet":           {"/path/to/dump.txt"},
	"invalidateblock":        {"BLOCKHASH"},
	"keypoolrefill":          {100},
	"listreceivedbyaccount":  {0, true, true},
	"listreceivedbyaddress":  {0, true, true},
	"listreceivedbylabel":    {0, true, true},
	"listsinceblock":         {"BLOCKHASH", 1, true},
	"listtransactions":       {"*", 10, 0, true},
	"listunspent":            {0, 9999999, []any{"WALLET"}},
	"lockunspent":            {false, []any{map[string]any{"txid": "TXID", "vout": 0}}},
	"move":                   {"from", "to", 1.0, 0, "memo"},
	"prioritisetransaction":  {"TXID", 0, 1000},
	"pruneblockchain":        {550},
	"preciousblock":          {"BLOCKHASH"},
	"reconsiderblock":        {"BLOCKHASH"},
	"reindextx":              {false},
	"removeprunedfunds":      {"TXID"},
	"rescan":                 {0},
	"sendfrom":               {"from", "WALLET", 1.0, 1, "memo"},
	"sendmany":               {"from", map[string]any{"WALLET": 1.0}, 1, "memo"},
	"sendrawtransaction":     {"HEX"},
	"submitpackage":          {[]any{"HEX1", "HEX2"}},
	"sendtoaddress":          {"WALLET", 10.0},
	"setaccount":             {"WALLET", "default"},
	"setban":                 {"192.168.1.50/32", "add", 86400},
	"setlabel":               {"WALLET", "receive"},
	"setmaxconnections":      {32},
	"setmocktime":            {1700000000},
	"setnetworkactive":       {true},
	"settxfee":               {0.01},
	"setwalletflag":          {"avoid_reuse", true},
	"signmessage":            {"WALLET", "hello"},
	"signmessagewithprivkey": {"WHEX", "hello"},
	"signrawtransaction":     {"HEX", []any{}, []any{"WHEX1", "WHEX2"}, "ALL"},
	"signrawtransactionwithkey": {"HEX", []any{map[string]any{"WALLET": "WHEX"}}},
	"signrawtransactionwithwallet": {"HEX"},
	"signerdisplayaddress":   {"WALLET"},
	"simulaterawtransaction": {[]any{"HEX"}, map[string]any{}},
	"submitauxblock":         {"HASH", "AUXPOW_HEX"},
	"submitblock":            {"HEX"},
	"testmempoolaccept":      {[]any{"HEX"}},
	"truncatetoheight":       {100},
	"validateaddress":        {"WALLET"},
	"verifychain":            {3},
	"verifymessage":          {"WALLET", "signature", "hello"},
	"verifytxoutproof":       {"PROOF", []any{"TXID"}},
	"descriptorprocesspsbt":  {"PSBT_HEX", []any{"addr(WALLET)"}, true},
	"walletcreatefundedpsbt": {
		[]any{map[string]any{"txid": "TXID", "vout": 0}},
		[]any{map[string]any{"WALLET": map[string]any{"": 10.0}}},
		0,
		map[string]any{"replaceable": true},
	},
	"walletpassphrase":       {"passphrase", 60},
	"walletpassphrasechange": {"old", "new"},
	"walletprocesspsbt":      {"PSBT_HEX", true, "ALL"},
	"waitforblock":           {"BLOCKHASH", 60},
	"waitforblockheight":     {100, 60},
	"waitfornewblock":        {60},
}
