// Copyright (c) 2026 Paulo Vidal (https://x.com/inevitable360, https://github.com/qlpqlp)
// Copyright (c) 2026 Dogecoin Foundation
//
// SPDX-License-Identifier: MIT
// See LICENSE for copyright attribution to upstream Bitcoin/Dogecoin Core.

package wire

import "strconv"

// OpcodeName returns the Core script GetOpName string for standard opcodes (decodescript asm).
func OpcodeName(op byte) string {
	switch op {
	case 0x00:
		return "0"
	case 0x4c:
		return "OP_PUSHDATA1"
	case 0x4d:
		return "OP_PUSHDATA2"
	case 0x4e:
		return "OP_PUSHDATA4"
	case 0x4f:
		return "OP_1NEGATE"
	case 0x50:
		return "OP_RESERVED"
	case 0x61:
		return "OP_NOP"
	case 0x62:
		return "OP_VER"
	case 0x63:
		return "OP_IF"
	case 0x64:
		return "OP_NOTIF"
	case 0x65:
		return "OP_VERIF"
	case 0x66:
		return "OP_VERNOTIF"
	case 0x67:
		return "OP_ELSE"
	case 0x68:
		return "OP_ENDIF"
	case 0x69:
		return "OP_VERIFY"
	case 0x6a:
		return "OP_RETURN"
	case 0x6b:
		return "OP_TOALTSTACK"
	case 0x6c:
		return "OP_FROMALTSTACK"
	case 0x6d:
		return "OP_2DROP"
	case 0x6e:
		return "OP_2DUP"
	case 0x6f:
		return "OP_3DUP"
	case 0x70:
		return "OP_2OVER"
	case 0x71:
		return "OP_2ROT"
	case 0x72:
		return "OP_2SWAP"
	case 0x73:
		return "OP_IFDUP"
	case 0x74:
		return "OP_DEPTH"
	case 0x75:
		return "OP_DROP"
	case 0x76:
		return "OP_DUP"
	case 0x77:
		return "OP_NIP"
	case 0x78:
		return "OP_OVER"
	case 0x79:
		return "OP_PICK"
	case 0x7a:
		return "OP_ROLL"
	case 0x7b:
		return "OP_ROT"
	case 0x7c:
		return "OP_SWAP"
	case 0x7d:
		return "OP_TUCK"
	case 0x7e:
		return "OP_CAT"
	case 0x7f:
		return "OP_SUBSTR"
	case 0x80:
		return "OP_LEFT"
	case 0x81:
		return "OP_RIGHT"
	case 0x83:
		return "OP_INVERT"
	case 0x84:
		return "OP_AND"
	case 0x85:
		return "OP_OR"
	case 0x86:
		return "OP_XOR"
	case 0x82:
		return "OP_SIZE"
	case 0x87:
		return "OP_EQUAL"
	case 0x88:
		return "OP_EQUALVERIFY"
	case 0x89:
		return "OP_RESERVED1"
	case 0x8a:
		return "OP_RESERVED2"
	case 0x8b:
		return "OP_1ADD"
	case 0x8c:
		return "OP_1SUB"
	case 0x8d:
		return "OP_2MUL"
	case 0x8e:
		return "OP_2DIV"
	case 0x8f:
		return "OP_NEGATE"
	case 0x90:
		return "OP_ABS"
	case 0x91:
		return "OP_NOT"
	case 0x92:
		return "OP_0NOTEQUAL"
	case 0x93:
		return "OP_ADD"
	case 0x94:
		return "OP_SUB"
	case 0x95:
		return "OP_MUL"
	case 0x96:
		return "OP_DIV"
	case 0x97:
		return "OP_MOD"
	case 0x98:
		return "OP_LSHIFT"
	case 0x99:
		return "OP_RSHIFT"
	case 0x9a:
		return "OP_BOOLAND"
	case 0x9b:
		return "OP_BOOLOR"
	case 0x9c:
		return "OP_NUMEQUAL"
	case 0x9d:
		return "OP_NUMEQUALVERIFY"
	case 0x9e:
		return "OP_NUMNOTEQUAL"
	case 0x9f:
		return "OP_LESSTHAN"
	case 0xa0:
		return "OP_GREATERTHAN"
	case 0xa1:
		return "OP_LESSTHANOREQUAL"
	case 0xa2:
		return "OP_GREATERTHANOREQUAL"
	case 0xa3:
		return "OP_MIN"
	case 0xa4:
		return "OP_MAX"
	case 0xa5:
		return "OP_WITHIN"
	case 0xa6:
		return "OP_RIPEMD160"
	case 0xa8:
		return "OP_SHA256"
	case 0xa9:
		return "OP_HASH160"
	case 0xaa:
		return "OP_HASH256"
	case 0xab:
		return "OP_CODESEPARATOR"
	case 0xac:
		return "OP_CHECKSIG"
	case 0xad:
		return "OP_CHECKSIGVERIFY"
	case 0xae:
		return "OP_CHECKMULTISIG"
	case 0xaf:
		return "OP_CHECKMULTISIGVERIFY"
	case 0xb0:
		return "OP_NOP1"
	case 0xb1:
		return "OP_CHECKLOCKTIMEVERIFY"
	case 0xb2:
		return "OP_CHECKSEQUENCEVERIFY"
	case 0xb3:
		return "OP_NOP4"
	case 0xb4:
		return "OP_NOP5"
	case 0xb5:
		return "OP_NOP6"
	case 0xb6:
		return "OP_NOP7"
	case 0xb7:
		return "OP_NOP8"
	case 0xb8:
		return "OP_NOP9"
	case 0xb9:
		return "OP_NOP10"
	default:
		if op >= 0x51 && op <= 0x60 {
			return strconv.Itoa(int(op - 0x50))
		}
		return ""
	}
}
